config/routes.rb
Rails.application.routes.draw do
  resources :wages

  root 'wages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wage.rb
class Wage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/wages_controller.rb
class WagesController < ApplicationController
  before_action :set_wage, only: [:show, :edit, :update, :destroy]

  # GET /wages
  # GET /wages.json
  def index
    @wages = Wage.all
    @wages.each do |wage|
      wage.billable = billable(wage)
    end
  end

  # GET /wages/1
  # GET /wages/1.json
  def show
    @wage.billable = billable(@wage)
  end

  # GET /wages/new
  def new
    @wage = Wage.new
  end

  # GET /wages/1/edit
  def edit
  end

  # POST /wages
  # POST /wages.json
  def create
    @wage = Wage.new(wage_params)

    respond_to do |format|
      if @wage.save
        format.html { redirect_to @wage, notice: 'Wage was successfully created.' }
        format.json { render :show, status: :created, location: @wage }
      else
        format.html { render :new }
        format.json { render json: @wage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wages/1
  # PATCH/PUT /wages/1.json
  def update
    respond_to do |format|
      if @wage.update(wage_params)
        format.html { redirect_to @wage, notice: 'Wage was successfully updated.' }
        format.json { render :show, status: :ok, location: @wage }
      else
        format.html { render :edit }
        format.json { render json: @wage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wages/1
  # DELETE /wages/1.json
  def destroy
    @wage.destroy
    respond_to do |format|
      format.html { redirect_to wages_url, notice: 'Wage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def billable(wage)
    billable_wages = 0
    if (wage.hours != nil)
      billable_wages += (wage.hours * wage.hourly_rate)
    end
    if (wage.minutes != nil)
      billable_wages += ((wage.minutes / 60.0) * wage.hourly_rate)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wage
      @wage = Wage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wage_params
      params.require(:wage).permit(:date, :hours, :minutes, :hourly_rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wages_helper.rb
module WagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WageCalculator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/wages/_form.html.erb
<%= form_for(wage) do |f| %>
  <% if wage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wage.errors.count, "error") %> prohibited this wage from being saved:</h2>

      <ul>
      <% wage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :hours %>
    <%= f.number_field :hours %>
  </div>

  <div class="field">
    <%= f.label :minutes %>
    <%= f.number_field :minutes %>
  </div>

  <div class="field">
    <%= f.label :hourly_rate %>
    <%= f.number_field :hourly_rate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wages/edit.html.erb
<h1>Editing Wage</h1>

<%= render 'form', wage: @wage %>

<%= link_to 'Show', @wage %> |
<%= link_to 'Back', wages_path %>

app/views/wages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wages</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Hours</th>
      <th>Minutes</th>
      <th>Hourly rate</th>
      <th>Billable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wages.each do |wage| %>
      <tr>
        <td><%= wage.date %></td>
        <td><%= wage.hours %></td>
        <td><%= wage.minutes %></td>
        <td><%= wage.hourly_rate %></td>
        <td><%= wage.billable %></td>
        <td><%= link_to 'Show', wage %></td>
        <td><%= link_to 'Edit', edit_wage_path(wage) %></td>
        <td><%= link_to 'Destroy', wage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wage', new_wage_path %>

app/views/wages/new.html.erb
<h1>New Wage</h1>

<%= render 'form', wage: @wage %>

<%= link_to 'Back', wages_path %>

app/views/wages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @wage.date %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @wage.hours %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @wage.minutes %>
</p>

<p>
  <strong>Hourly rate:</strong>
  <%= @wage.hourly_rate %>
</p>

<%= link_to 'Edit', edit_wage_path(@wage) %> |
<%= link_to 'Back', wages_path %>